DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view=views.HomeView.as_view(), name='home'),
    path('bible/', include('bible.urls'))
]

bible/urls.py
from django.urls import path
from . import views

app_name = 'bible'

urlpatterns = [
    path('bible', view=views.BibleView.as_view(), name='bible'),
    path('mcheyne', view=views.McheyneView.as_view(), name='mcheyne'),
    path('bible/<str:book>/<int:chapter>', view=views.DataView.as_view(), name="bible_book")
]

bible/models.py
from django.db import models

# Create your models here.


class BibleModel(models.Model):
    book = models.CharField(max_length=3)
    chapter = models.PositiveSmallIntegerField()
    verse = models.PositiveSmallIntegerField()
    contents = models.TextField()

    def __str__(self):
        return f"{self.book} {self.chapter}:{self.verse} {self.contents}"


class BibleMetaModel(models.Model):
    book = models.CharField(max_length=3)
    full_name = models.CharField(max_length=15)
    testament = models.CharField(max_length=3)
    chapter_length = models.PositiveSmallIntegerField()
    verse_length = models.PositiveSmallIntegerField()

    def __str__(self):
        return f"{self.full_name}"


class McheyneModel(models.Model):
    month = models.PositiveSmallIntegerField()
    day = models.PositiveSmallIntegerField()
    order = models.PositiveIntegerField()
    part1 = models.CharField(max_length=30)
    part2 = models.CharField(max_length=30)
    part3 = models.CharField(max_length=30)
    part4 = models.CharField(max_length=30)
    part1_start_book = models.CharField(max_length=3)
    part1_start_chapter = models.PositiveIntegerField()
    part1_start_verse = models.PositiveIntegerField()
    part1_end_book = models.CharField(max_length=3)
    part1_end_chapter = models.PositiveIntegerField()
    part1_end_verse = models.PositiveIntegerField()
    part2_start_book = models.CharField(max_length=3)
    part2_start_chapter = models.PositiveIntegerField()
    part2_start_verse = models.PositiveIntegerField()
    part2_end_book = models.CharField(max_length=3)
    part2_end_chapter = models.PositiveIntegerField()
    part2_end_verse = models.PositiveIntegerField()
    part3_start_book = models.CharField(max_length=3)
    part3_start_chapter = models.PositiveIntegerField()
    part3_start_verse = models.PositiveIntegerField()
    part3_end_book = models.CharField(max_length=3)
    part3_end_chapter = models.PositiveIntegerField()
    part3_end_verse = models.PositiveIntegerField()
    part4_start_book = models.CharField(max_length=3)
    part4_start_chapter = models.PositiveIntegerField()
    part4_start_verse = models.PositiveIntegerField()
    part4_end_book = models.CharField(max_length=3)
    part4_end_chapter = models.PositiveIntegerField()
    part4_end_verse = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.order}일차, {self.month}/{self.day} {self.part1} / {self.part2} / {self.part3} / {self.part4}"

DjangoApp/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

bible/views.py
from django.shortcuts import render
from django.core import serializers
from django.views.generic import TemplateView, View
from .models import BibleMetaModel, BibleModel, McheyneModel
from django.http import JsonResponse
import json
from datetime import datetime

# Create your views here.


class BibleView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meta"] = BibleMetaModel.objects.all()
        # context["meta_data"] = serializers.serialize('json', BibleMetaModel.objects.all())
        # context["bible"] = BibleModel.objects.all()
        # context["bible_data"] = serializers.serialize('json', BibleModel.objects.all())
        return context

    template_name = 'bible/bible.html'


class McheyneView(TemplateView):
    def get_context_data(self, **kwargs):
        today = datetime.now()

        query = McheyneModel.objects.filter(
            month=today.month, day=today.day).get()
        item = vars(query)
        data = []
        parts = []

        for i in range(1, 5):
            id_rng = []
            for j in ['start', 'end']:
                book = item.get(f'part{i}_{j}_book')
                chapter = item.get(f'part{i}_{j}_chapter')
                verse = item.get(f'part{i}_{j}_verse')
                id_rng.append(BibleModel.objects.filter(
                    book=book, chapter=chapter, verse=verse).get().id)
            data.append(BibleModel.objects.filter(id__range=id_rng))
            parts.append(item.get(f'part{i}'))

        list_data = [item.values() for item in data]

        context = super().get_context_data(**kwargs)
        context["today_mcheyne"] = query
        context["parts"] = parts
        context["today_data"] = list_data
        # context["mcheyne_data"] = serializers.serialize('json', McheyneModel.objects.all())
        # context["bible_data"] = serializers.serialize('json', BibleModel.objects.all())
        return context

    template_name = 'bible/mcheyne.html'


class DataView(View):
    def get(self, request, book, chapter=0):
        if not chapter:
            data = BibleModel.objects.filter(book=book)
        else:
            data = BibleModel.objects.filter(book=book, chapter=chapter)
        list_data = list(data.values())

        # fields = [ field.name for field in BibleModel._meta.get_fields() ]
        # list_data = { i:r for i, r in enumerate(list(data.values())) }
        # print(dict(data.values())[:5])
        # json_data = json.dumps( list(data.values()) )
        return JsonResponse(list_data, safe=False, json_dumps_params={'ensure_ascii': False})

bible/templates/bible/bible.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% load static %}
<!-- prettier-ignore -->
{% block head %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
  crossorigin="anonymous"
/>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
  crossorigin="anonymous"
></script>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'bible/css/style.css' %}"
/>

{% endblock head %} {% block contents %} {% load static %}

<h1>성경</h1>
<div class="container-fluid mt-3">
  {% for obj in meta %}
  <div
    class="btn btn-outline-primary btn-sm p-1 my-1 shadow"
    data-bs-toggle="tooltip"
    title="{{ obj.chapter_length }}장"
    onclick="displayData('{{obj.book}}'); displayChapter('{{obj.book}}', {{obj.chapter_length}})"
  >
    {{ obj.full_name }}
    <span class="badge rounded-pill bg-info">{{ obj.chapter_length }}</span>
  </div>
  {% endfor %}
</div>
<div class="container-fluid mt3">
  <div id="chapter_space"></div>
</div>
<div class="container-fluid mt3">
  <div id="text_space"></div>
</div>

<div id="testSpace"></div>

<template id="testTemplate">
  <div class="chapter">1</div>
  <div class="box">
    <div class="verse_number">2</div>
    <p>테스트</p>
  </div>
</template>

<script type="text/javascript" src="{% static 'bible/js/script.js' %}"></script>

<script>
  // title 변경
  let title = "성경";
  setNavTitle(title);
</script>
<!-- onclick="displayText('{{obj.book}}'); displayChapter('{{obj.book}}', {{obj.chapter_length}})"> -->
<!-- <script type="text/javascript">
  // 요소 선택 변수 지정
  let elText = document.getElementById("text_space");
  let elChapter = document.getElementById("chapter_space");

  // title 변경
  let title = "성경";
  setNavTitle(title);

  // 비동기 데이터 보여주는 함수
  async function displayData(book, chapter = 0) {
    // 데이터 추가할 DOM 요소 설정
    const testSpace = document.querySelector("#testSpace");
    // 데이터 가져오기
    let data = await getData(book, chapter);
    testSpace.innerHTML = ""; // 초기화
    for (const obj of data) {
      generateVerse(obj, testSpace); // 구절 데이터 생성
    }
  }

  // Data 가져오는 fetch
  function getData(book, chapter = 0) {
    let url = `/bible/bible/` + encodeURIComponent(book) + "/" + chapter;
    return fetch(url)
      .then((response) => response.json())
      .then((data) => {
        return data;
      })
      .catch((error) => console.error(error));
  }

  // 장을 표시하는 함수
  function displayChapter(book, chapter_length) {
    elChapter.innerHTML = "";
    for (let index = 1; index < chapter_length + 1; index++) {
      span = document.createElement("span");
      span.classList.add("btn", "btn-outline-primary", "btn-sm");
      span.append(`${index}`);
      elChapter.appendChild(span);
      span.addEventListener("click", () => {
        displayData(book, index);
      });
    }
  }

  function generateVerse(obj, space) {
    // 1절인 경우 장 생성
    if (obj.verse === 1) {
      const div = document.createElement("div");
      div.classList.add("chapter");
      div.textContent = obj.chapter;
      space.append(div);
    }
    // 박스 생성
    const box = document.createElement("div");
    box.classList.add("box");

    // 절 번호 추가
    const verseNumber = document.createElement("div");
    verseNumber.classList.add("verse_number");
    verseNumber.textContent = obj.verse;

    // 절 내용 추가
    const verse = document.createElement("p");
    verse.textContent = obj.contents;

    // 박스에 자식 요소들을 추가
    box.appendChild(verseNumber);
    box.appendChild(verse);

    space.appendChild(box); // HTML 요소에 추가
  }

  function setNavTitle(title) {
    document.getElementById("nav-title").innerText = title;
  }
</script> -->
{% endblock contents %}

<!-- 사용하지 않는 스크립트 -->
<script>
  // let metaData = {{ meta_data | safe }}
  // let bibleData = {{ bible_data | safe }}

  //   function displayText(book, chapter = 0) {
  //   elText.innerHTML = "";
  //   const full_name = metaData.find((item) => item.fields.book === book)?.fields
  //     .full_name;
  //   elText.innerHTML = `
  //   <div class="upside">${full_name} ${
  //     chapter == 0 ? "전체" : chapter
  //   }장</div><hr>`;
  //   // document.createElement('hr')
  //   if (chapter) {
  //     // 장이 있는 경우 각 장
  //     filtered = bibleData.filter(
  //       (data) => data.fields.book === book && data.fields.chapter == chapter
  //     );

  //     filtered.forEach((data, index) => {
  //       if (index === 0) {
  //         const div = document.createElement("div");
  //         div.classList.add("chapter");
  //         div.textContent = data.fields.chapter;
  //         elText.append(div);
  //       }
  //       generateVerse(data);
  //     });
  //   } else {
  //     // 장이 없는 경우 전체 장
  //     filtered = bibleData.filter((data) => data.fields.book === book);

  //     filtered.forEach((data) => {
  //       if (data.fields.verse === 1) {
  //         const div = document.createElement("div");
  //         div.classList.add("chapter");
  //         div.textContent = data.fields.chapter;
  //         elText.append(div);
  //       }
  //       generateVerse(data);
  //     });

  //   }
  // }

  // function generateVerse(data, index) {
  //   // 박스 생성
  //   const box = document.createElement('div');
  //   box.classList.add('box');

  //   // 절 번호 추가
  //   const verseNumber = document.createElement('div');
  //   verseNumber.classList.add('verse_number');
  //   verseNumber.textContent = data.fields.verse

  //   // 절 내용 추가
  //   const verse = document.createElement('p');
  //   verse.textContent = data.fields.contents

  //   // 박스에 자식 요소들을 추가
  //   box.appendChild(verseNumber);
  //   box.appendChild(verse);

  //   elText.appendChild(box) // HTML 요소에 추가
  // }

  // for (const data of bibleData) {
  //   if (data.fields.book === book) {
  //     text = document.createTextNode(`${data.fields.contents}`)
  //     paragrpah = document.createElement('p')
  //     paragrpah.appendChild(text)
  //     elText.appendChild(paragrpah)
  //   }
  // }
</script>
<!-- Horizontal under breakpoint -->

bible/templates/bible/mcheyne.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% load static %}
<!-- prettier-ignore -->
{% block contents %} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'bible/css/style.css' %}"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'bible/css/mcheyne.css' %}"
/>

{% endblock head %}
<div id="main">
  <!-- 제목 -->
  <h2>오늘의 맥체인 성경말씀</h2>

  <!-- 날짜 -->
  <div id="date">
    {{ today_mcheyne.month }}월 {{ today_mcheyne.day }}일
    ({{today_mcheyne.order}}일차)
  </div>

  <!-- 맥체인 파트 리스트 -->
  <div id="part-list">
    <ol>
      {% for part in parts %}
      <li><a href="#part{{ forloop.counter }}">{{part}}</a></li>
      {% endfor %}
    </ol>
  </div>

  <!-- 맥체인 내용 부분 -->
  <div id="mc_container">
    <!-- 파트1 -->
    <hr />
    <div class="part-name" id="part1">part1. {{ today_mcheyne.part1 }}</div>
    <hr />
    {% for item in today_data.0 %} {% if item.verse == 1 %}
    <div class="chapter">{{ item.chapter }}</div>
    {% endif %}
    <div class="box">
      <div class="verse_number">{{ item.verse }}</div>
      <p>{{ item.contents }}</p>
    </div>
    {% endfor %}

    <!-- 파트2 (반복 리팩토링 필요)-->
    <hr />
    <div class="part-name" id="part2">part2. {{ today_mcheyne.part2 }}</div>
    <hr />
    {% for item in today_data.1 %} {% if item.verse == 1 %}
    <div class="chapter">{{ item.chapter }}</div>
    {% endif %}
    <div class="box">
      <div class="verse_number">{{ item.verse }}</div>
      <p>{{ item.contents }}</p>
    </div>
    {% endfor %}

    <!-- 파트3 (반복 리팩토링 필요)-->
    <hr />
    <div class="part-name" id="part3">part3. {{ today_mcheyne.part3 }}</div>
    <hr />
    {% for item in today_data.2 %} {% if item.verse == 1 %}
    <div class="chapter">{{ item.chapter }}</div>
    {% endif %}
    <div class="box">
      <div class="verse_number">{{ item.verse }}</div>
      <p>{{ item.contents }}</p>
    </div>
    {% endfor %}

    <!-- 파트4 (반복 리팩토링 필요)-->
    <hr />
    <div class="part-name" id="part4">part4. {{ today_mcheyne.part4 }}</div>
    <hr />
    {% for item in today_data.3 %} {% if item.verse == 1 %}
    <div class="chapter">{{ item.chapter }}</div>
    {% endif %}
    <div class="box">
      <div class="verse_number">{{ item.verse }}</div>
      <p>{{ item.contents }}</p>
    </div>
    {% endfor %}
  </div>
</div>

<!-- JS 추가 -->
<script type="text/javascript" src="{% static 'bible/js/script.js' %}"></script>

<!-- Title 설정 -->
<script>
  let title = "오늘의 맥체인";
  setNavTitle(title);
</script>

{% endblock contents %}

bible/templates/bible/source.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<h1>source</h1>

{% endblock contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
  <head>
    <meta charset="UTF-8" />
    <title>성경과 맥체인 : 장원 연습페이지</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'bible/css/main.css'%}" />
    <!-- 부트스트랩 걷어내기 -->
    {% block head %}{% endblock head %}
  </head>

  <body>
    <!-- Navbar -->
    <nav>
      <div class="left-side">
        <div id="nav-title"></div>
      </div>
      <div class="right-side">
        <div id="darkModeIcon">🌙</div>
        <div id="menu-bar"></div>
      </div>
    </nav>
    {% block contents %}{% endblock contents %}
    <script>
      const menu = document.getElementById("menu-bar");
      menu.addEventListener("click", menuHandler);
      function menuHandler() {
        menu.innerHTML = "";
        let div = document.createElement("div");
        div.id = "menu-box";
        div.innerHTML = `
        <a href="{% url 'bible:bible' %}">성경</a>
    <a href="{% url 'bible:mcheyne' %}">맥체인</a>
`;
        menu.appendChild(div);
      }
    </script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<h1>home</h1>

{% endblock contents %}